name: Release

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Download artifacts from the CI/CD pipeline build job
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          pattern: espressobar-*
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}

      - name: Organize artifacts for release
        run: |
          mkdir -p dist/
          
          echo "Debug: Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Debug: Current working directory:"
          pwd
          
          echo "Debug: Contents of current directory:"
          ls -la
          
          echo "Debug: Contents of artifacts/ directory:"
          find artifacts/ -type f -ls 2>/dev/null || echo "No artifacts directory found"
          
          # Move all binary files to dist/ directory
          find artifacts/ -type f \( -name "*.dmg" -o -name "*.zip" -o -name "*.exe" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.tar.gz" \) -exec mv {} dist/ \; 2>/dev/null || echo "No binary files found to move"
          
          echo "Debug: Contents of dist/ directory after move:"
          ls -la dist/
          
          # If no files were found, try alternative approach
          if [ -z "$(ls -A dist/ 2>/dev/null)" ]; then
            echo "Warning: No binary files found in artifacts. Checking for any files..."
            find artifacts/ -type f -exec echo "Found file: {}" \;
          fi

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release 
